In [1]:
import numpy as np

In [250]:
sentences = [[26, 67, 79], [72, 71, 28], [26, 67, 64], [60, 63, 28], [26, 79, 68], [79, 71, 64]]

### Concatenation in for loop

In [251]:
np_sentences = np.array([sentences[0]])
print(np_sentences)
np_sentences.shape

[[26 67 79]]


(1, 3)

In [252]:
for elem in sentences[1:-2]:
    elem = np.array([elem])
    np_sentences = np.concatenate((np_sentences, elem), axis=0)
print(np_sentences)
np_sentences.shape

[[26 67 79]
 [72 71 28]
 [26 67 64]
 [60 63 28]]


(4, 3)

### List comprehension concatination

In [253]:
np_sentences_2 = np.concatenate([[np.array(elem)] for elem in sentences[:-2]])
print(np_sentences_2)
np_sentences_2.shape

[[26 67 79]
 [72 71 28]
 [26 67 64]
 [60 63 28]]


(4, 3)

In [256]:
type(np_sentences) == type(np_sentences_2)

True

In [257]:
np_sentences == np_sentences_2

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]], dtype=bool)