In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3])

In [3]:
y = np.random.rand(4,5)

In [4]:
print(x,y)

[1 2 3] [[ 0.11358207  0.16119631  0.48607755  0.36881291  0.5766336 ]
 [ 0.30813829  0.04243911  0.21241625  0.96238761  0.33507245]
 [ 0.45358284  0.94793668  0.28581916  0.58043343  0.01715032]
 [ 0.26109831  0.27985212  0.8477972   0.94037222  0.66067557]]


In [6]:
y.sort()

In [7]:
print(y)

[[ 0.11358207  0.16119631  0.36881291  0.48607755  0.5766336 ]
 [ 0.04243911  0.21241625  0.30813829  0.33507245  0.96238761]
 [ 0.01715032  0.28581916  0.45358284  0.58043343  0.94793668]
 [ 0.26109831  0.27985212  0.66067557  0.8477972   0.94037222]]


In [9]:
y[2,4]

0.94793667914399282

In [11]:
np.multiply(y,0.5)

array([[ 0.05679103,  0.08059816,  0.18440645,  0.24303877,  0.2883168 ],
       [ 0.02121956,  0.10620813,  0.15406915,  0.16753622,  0.4811938 ],
       [ 0.00857516,  0.14290958,  0.22679142,  0.29021672,  0.47396834],
       [ 0.13054916,  0.13992606,  0.33033779,  0.4238986 ,  0.47018611]])

In [20]:
z = np.random.rand(4,5)
np.multiply(y,z)

array([[ 0.09171226,  0.03525498,  0.04154922,  0.42031444,  0.15890226],
       [ 0.00878337,  0.15845667,  0.1475772 ,  0.00736654,  0.55610749],
       [ 0.01366667,  0.04939397,  0.13748633,  0.39369087,  0.2570047 ],
       [ 0.04003154,  0.23752677,  0.087911  ,  0.78826479,  0.69709669]])

In [21]:
np.abs(z)

array([[ 0.80745368,  0.21870838,  0.11265663,  0.86470655,  0.27556885],
       [ 0.20696395,  0.74597246,  0.47893172,  0.02198492,  0.57784149],
       [ 0.79687569,  0.17281545,  0.30311184,  0.6782705 ,  0.27112011],
       [ 0.15331978,  0.84875815,  0.13306228,  0.92977989,  0.74129868]])

In [28]:
np.var(z)

0.090206198934967965