In [2]:
import numpy as np

### Broadcasting examples

#### example 1

In [11]:
np.array([1,2,3]) - 2 #broadcasting scalar across 3 element of vector 

array([-1,  0,  1])

#### example 2 - prepending unit axes

In [7]:
#example
#its taking two tensors
np.array([2,3]).reshape(1,1,1,2) #first take tensor with shorter dimensions 
#prepend unit axes to the front
#1,1,1 -three unit axes to the front
#now its 4 dimensional tensor

array([[[[2, 3]]]])

In [9]:
#example 2
np.array([2,3]).reshape(1,1,2,1)

array([[[[2],
         [3]]]])

#### example 3

In [13]:
a = np.random.randn(5,1,3,2) #4 dimensional tensor
#2 columns, 3 rows, 1 slice, 5 tubes
b = np.random.randn(2) #vector of length 2
(a-b).shape #goint to reshape tensor with shorter dimesion be prepending unit axes -b = np.random.randn(2).reshape(1,1,1,2)
#then it goin to 1 by 3 times, 1 by 1 time, 1 bu 5 times
#thus its going to substract b vector from every row, every slice, every tube

(5, 1, 3, 2)