In [1]:
import numpy as np

In [242]:
sentences = [[26, 67, 79], [72, 71, 28], [26, 67, 64], [60, 63, 28], [26, 79, 68], [79, 71, 64]]
np_sentences = np.array([sentences[0]])
print(np_sentences)
np_sentences.shape

[[26 67 79]]


(1, 3)

In [243]:
for elem in sentences[1:-2]:
    elem = np.array([elem])
    np_sentences = np.concatenate((np_sentences, elem), axis=0)
print(np_sentences)

[[26 67 79]
 [72 71 28]
 [26 67 64]
 [60 63 28]]


In [244]:
np_sentences.shape

(4, 3)