In [1]:
from scipy import linalg, sparse

In [2]:
import numpy as np

In [4]:
A = np.matrix(np.random.random((2,2)))

In [5]:
A

matrix([[ 0.17572206,  0.68841245],
        [ 0.19958734,  0.31789752]])

In [7]:
B = np.mat([[3,4],[5,6]])

In [8]:
B

matrix([[3, 4],
        [5, 6]])

In [11]:
linalg.det(A)

-0.08153680125769402

In [12]:
J = sparse.dok_matrix(A)

In [13]:
J

<2x2 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Dictionary Of Keys format>

In [14]:
A

matrix([[ 0.17572206,  0.68841245],
        [ 0.19958734,  0.31789752]])

In [17]:
np.dot(A,B)

matrix([[ 3.96922843,  4.83336294],
        [ 2.18824963,  2.70573449]])

In [18]:
np.vdot(A,B)

matrix([[ 0.52716619]])

In [19]:
linalg.expm(A)

array([[ 1.27902423,  0.90219275],
       [ 0.2615674 ,  1.465351  ]])

In [20]:
linalg.logm(B)

array([[-0.24950826+2.07030856j,  1.58955161-1.33203262j],
       [ 1.98693952-1.66504078j,  0.94265545+1.07128409j]])

In [22]:
linalg.sqrtm(B)

array([[ 1.03525981+0.30697685j,  1.28724010-0.19750833j],
       [ 1.60905012-0.24688541j,  2.00068989+0.15884561j]])